services:
  back:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "3006:3006"
    depends_on:
      - back
  postgres:
    image: "postgres:17"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
